#!/usr/bin/env ruby

Signal.trap("INT") { exit 1 }

require "optparse"
require "tty-color"

options = {}

ARGV << "-h" if ARGV.empty?

parser = OptionParser.new do |opts|
  opts.on("-m", "--mode", "Check number of supported colors") do
    options[:mode] = true
  end

  opts.on("-s", "--support", "Check terminal for color support") do
    options[:color] = true
  end

  options[:verbose] = false
  opts.on("-d", "--debug", "Display debug information" ) do
    options[:verbose] = true
  end

  opts.on("-h", "--help", "Display help" ) do
    puts opts
    exit
  end

  opts.on("-v", "--version", "Display the version") do
    puts "0.3.0 (tty-color #{TTY::Color::VERSION})"
    exit
  end
end

begin
  parser.parse!
rescue OptionParser::ParseError => error
  $stderr.puts error.message
  exit 1
end

TTY::Color.verbose = options[:verbose]

puts(options[:mode] ? TTY::Color.mode : TTY::Color.color?)
