#!/usr/bin/env ruby

Signal.trap("INT") { exit 1 }

require "optparse"
require "tty-color"

options = {}

parser = OptionParser.new do |opts|
  opts.on("-m", "--mode", "Check number of supported colors") do
    options[:mode] = true
  end

  opts.on("-s", "--support", "Check terminal for color support") do
    options[:color] = true
  end

  options[:verbose] = false
  opts.on("-d", "--debug", "Display debug information" ) do
    options[:verbose] = true
  end

  opts.on("-h", "--help", "Display help" ) do
    puts opts
    exit
  end
end

parser.parse!

TTY::Color.verbose = options[:verbose]

puts(options[:mode] ? TTY::Color.mode : TTY::Color.color?)
